spring:
    datasource:
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
        password: 
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /console
            
security:
    jwt:
        token:
            secret-key: $S%#E^DR&TF*YB(NU(
            expire-length: 3600000               